elems:

  - src:  ^config/(.+)$
    dst:  ~/.config/uzbl/<1>
    only: f?uzbl

  - src:  ^data/([^/]+)$
    dst:  ~/.local/share/uzbl/<1>
    only: f?uzbl

  - # Executable scripts.
    src:  ^data/scripts/(.+\.(?:sh|rb|py))$
    dst:  ~/.local/share/uzbl/scripts/<1>
    perms: 755
    only: f?uzbl

  - # Non-Executable scripts.
    src:   ^data/scripts/(.+\.(?!.*(?:sh|rb|py)).+)$
    dst:   ~/.local/share/uzbl/scripts/<1>
    only:  f?uzbl


# vim: set filetype: eruby.vim :
